---
- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 86400 #One day
  register: result

- name: List outdated packages
  debug: 
    msg: "{{ result.stdout_lines }}"

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
