---
- include_tasks: apt-upgrade-packages.yml
  when: ansible_facts['os_family'] in ['Debian']
  
- include_tasks: yum-upgrade-packages.yml
  when: ansible_facts['os_family'] in ['RedHat', 'CentOS', 'Rocky']
