---
- name: Trigger systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart the k3s service
  ansible.builtin.service:
    name: "{{ systemd_unit_name }}"
    state: restarted
