---
########################################################################################################################
### Общие параметры для хостов группы ##################################################################################

systemctl_path: /etc/systemd/system
log_main_address: ""

########################################################################################################################
### /ETC/HOSTS #########################################################################################################

# Сборка /etc/hosts файла из темплейта развертываания hosts
populate_inventory_to_hosts_file: true

########################################################################################################################
### PACKAGES ###########################################################################################################

common_packages:
  - java-17-openjdk
  - telnet
  - net-tools
  - tcpdump
  - traceroute
  - rsync

common_unnecessary_packages:
  - openldap-clients

########################################################################################################################
### USERS ##############################################################################################################

# Список пользователей для добавления на все сервера ZAPK
common_users_list:
  - name: "palmer"
    group: "users"
    comment: "Евдокимов Никита - devops инженер"
    # Публичный ключ пользователя для доступа к серверам по ключам
    key: ""
