---
- name: Pull service facts
  ansible.builtin.service_facts:

- name: Legacy agent remove
  block:
    - name: ZABBIX | LEGACY | Make sure the old zabbix-agent service stopped
      become: true
      ansible.builtin.service:
        name: "{{ zabbix_agent_service_name | replace('agent2', 'agent') }}"
        state: stopped
        enabled: false

    - name: ZABBIX | LEGACY | Package removal
      become: true
      ansible.builtin.package:
        name: "{{ zabbix_agent_package | replace('agent2', 'agent') }}"
        state: absent

    - name: ZABBIX | LEGACY | Remove the agent-include-dir
      become: true
      ansible.builtin.file:
        path: "{{ zabbix_agent_include_dir | replace('agent2', 'agent') }}"
        state: absent
  when:
    - ( ansible_facts.services["zabbix-agent.service"] is defined ) or
      ( ansible_facts.services["zabbix-agent"] is defined )
  tags: ['legacy']
