---
- name: KESL | Be sure kesl agent is installed
  become: true
  ansible.builtin.package:
    name: "{{ kesl_service_name }}"
    state: present
    update_cache: yes
    disable_gpg_check: true

- name: Creating answer file for kesl
  become: true
  ansible.builtin.template:
    src: "kesl.j2.ini"
    dest: "/tmp/kesl.ini"
    mode: '0644'

- name: Kesl postinstall config
  become: true
  ansible.builtin.shell: "{{ kesl_default_bin_path }}/kesl-setup.pl --autoinstall=/tmp/kesl.ini"
  register: postconfig_result
  notify: restart-kesl

- name: Be sure kesl agent service started
  become: true
  ansible.builtin.systemd_service:
    name: "{{ kesl_service_name }}"
    enabled: yes
    state: started

- name: Kesl check status
  ansible.builtin.shell: "{{ kesl_default_bin_path }}/kesl-control -S --app-info"
  register: kesl_status
  notify: restart-kesl

#- name: Remove tempo files
#  become: true
#  ansible.builtin.file:
#    path: "{{ item }}"
#    state: absent
#  with_items:
#    - "/tmp/kesl.ini"
