---
- include_tasks: set_facts.yml
- include_tasks: binary.yml
- include_tasks: configuration.yml
- include_tasks: scripts.yml
- include_tasks: service.yml
- include_tasks: kubeconfig.yml
  when:
    - k3s_node_type == "server"
- include_tasks: token.yml
  when:
  - k3s_node_type == "server"
  - fetch_token | bool
