---
- include: set_facts.yml
- include: binary.yml
- include: configuration.yml
- include: scripts.yml
- include: service.yml
- include: kubeconfig.yml
  when:
    - k3s_node_type == "server"
- include: token.yml
  when:
  - k3s_node_type == "server"
  - fetch_token | bool
