---
# Для Debian/Ubuntu используется /usr/local/share/ca-certificates/ вместо /etc/pki/ca-trust/source/anchors/
- name: Check existing certs directory
  ansible.builtin.stat:
    path: "{{ item }}"
  loop:
    - /etc/pki/ca-trust/source/anchors/
    - /usr/local/share/ca-certificates/
  register: certificates_available_dir

- name: Distribute necessary certificates
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ certificates_available_dir.results.path }}"
    owner: root
    group: root
    mode: '0644'
  with_fileglob: files/*.crt

- name: Extract certs
  become: true
  ansible.builtin.shell: "{{ 'update-ca-certificates' if ansible_os_family in ['Debian', 'Ubuntu'] else 'update-ca-trust extract' | default('omit') }}"
