---
- name: Distribute necessary certificates to hosts
  become: true
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/pki/ca-trust/source/anchors/"
    owner: root
    group: root
    mode: '0644'
  with_fileglob: files/*.crt

- name: Extract certs
  become: true
  ansible.builtin.shell: update-ca-trust extract
