---
- name: Clean up unused packages
  become: true
  ansible.builtin.package:
    name: "{{ item | default ([]) }}"
    state: absent
  loop: "{{ common_unnecessary_packages }}"
  when: common_unnecessary_packages | length > 0

- name: COMMON PACKAGES | Be sure wanted packages are installed
  become: true
  ansible.builtin.package:
    name: "{{ item | default ([]) }}"
    state: present
    update_cache: yes
  loop: "{{ common_packages }}"
  when: common_packages | length > 0
