---
- name: "Clean up unused {{ item }}"
  become: true
  ansible.builtin.package:
    name: "{{ item | default ([]) }}"
    state: absent
  loop: "{{ common_unnecessary_packages }}"
  #TODO поменять default на проверку по бит весу when: common_unnecessary_packages > 0

- name: "COMMON PACKAGES | Be sure {{ item }} is installed"
  become: true
  ansible.builtin.package:
    name: "{{ item | default ([]) }}"
    state: present
    update_cache: yes
  loop: "{{ common_packages }}"
