---
- name: HOSTS | populate inventory into hosts file
  become: true
  ansible.builtin.blockinfile:
    dest: /etc/hosts
    block: |
      {% for target in play_hosts %}
      {{ hostvars[target].ansible_host }} {{ (hostvars[target]["ansible_facts"]["fqdn"]|default('')) + (' ' + (hostvars[target]["ansible_facts"]["hostname"]|default(''))) }}
      {% endfor %}
    marker: "# {mark} Ansible inventory hosts: {{ play_hosts }}"
    insertafter: EOF
    owner: root
    group: root
    mode: '0644'
    backup: true
