---
- name: Pull service facts
  ansible.builtin.service_facts:

- name: Print service facts
  ansible.builtin.debug:
    var: ansible_facts.services

- name: Install firewalld if not present
  when:
    - ansible_os_family in ['Debian', 'Ubuntu']
    - "'firewalld.service' not in ansible_facts.services"
  block:
    - name: Install firewalld
      become: true
      ansible.builtin.apt:
        name: firewalld
        state: present

    - name: Be sure firewalld service started
      become: true
      ansible.builtin.systemd_service:
        name: firewalld
        enabled: yes
        state: started
      notify: restart-firewalld

- name: Configure firewalld
  block:
    - name: Ensure firewalld is running
      become: true
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes
      register: firewalld_service

    - name: Allow SSH service
      become: true
      ansible.posix.firewalld:
        service: ssh
        permanent: true
        state: enabled

    - name: Open default ports
      become: true
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      loop: "{{ firewalld_default_ports }}"
      notify: reload-firewalld
  
  rescue:
    - name: Restore firewalld if failed
      ansible.posix.firewalld:
        state: reset