- name: Configure firewalld
  block:
    - name: Ensure firewalld is running
      become: true
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes
      register: firewalld_service

    - name: Allow SSH service
      become: true
      ansible.posix.firewalld:
        service: ssh
        permanent: true
        state: enabled

    - name: Open default ports
      become: true
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      loop: "{{ firewalld_default_ports }}"
      notify: reload-firewalld
  
  rescue:
    - name: Restore firewalld if failed
      ansible.posix.firewalld:
        state: reset