---
- name: Setting facts about current environment
  ansible.builtin.include_tasks:
    file: facts.yml
  tags: ['linux', 'always', 'check']

- name: Init host main attributes
  ansible.builtin.include_tasks:
    file: prerequirements.yml
  when: true
  tags: ['linux', 'always']

- name: SELinux manage policy
  ansible.builtin.include_tasks:
    file: selinux.yml
  when:
    - selinux_allowed | bool
    - selinux_enabled | bool
  tags: ['linux', 'selinux']

- name: VM settings tuning
  ansible.builtin.include_tasks:
    file: hardering.yml
  when: true
  tags: ['linux', 'always']

- name: Swap disabling
  ansible.builtin.include_tasks:
    file: swap.yml
  when: true
  tags: ['linux', 'always', 'swap']

- name: Configure /etc/hosts
  ansible.builtin.include_tasks:
    file: etc-hosts.yml
  when: populate_inventory_to_hosts_file
  tags: ['linux', 'hosts']

- name: Add custom repos if defined so
  ansible.builtin.include_tasks:
    file: custom_repositories.yml
  when:
    - use_custom_repositories
    - private_repository_is_available | default ('false')
  tags: ['linux', 'always']

- name: Install all OS updates
  ansible.builtin.include_tasks:
    file: updates.yml
  when: true
  tags: ['linux', 'always', 'updates']

- name: Setup firewalld
  ansible.builtin.include_tasks:
    file: firewalld.yml
  when: true
  tags: ['linux', 'always']

- name: Insert necessary certificates
  ansible.builtin.include_tasks:
    file: certs.yml
  when: true
  tags: ['linux', 'always']

- name: Configure users environment
  ansible.builtin.include_tasks:
    file: users.yml
  when: true
  tags: ['linux', 'user', 'always']

- name: Install required packages
  ansible.builtin.include_tasks:
    file: dependencies.yml
  when: true
  tags: ['linux', 'always']

- name: Monitoring & logging setup
  ansible.builtin.include_tasks:
    file: observing.yml
  when: true
  tags: ['linux', 'observing']

- name: SELinux AVC check after run
  ansible.builtin.include_tasks:
    file: se-avc-check.yml
  when: selinux_allowed | bool
  tags: ['linux', 'selinux', 'security']
