---
- name: CHRONY | service templating
  block:
    - name: Be sure chrony is installed
      become: true
      ansible.builtin.package:
        name: chrony
        state: present

    - name: Be sure chrony is configured
      become: true
      ansible.builtin.template:
        src: chrony.j2.conf
        dest: "{{ (ansible_os_family in ['Debian','Ubuntu']) | ternary('/etc/chrony/chrony.conf', '/etc/chrony.conf') }}"
        mode: '0644'
      notify: restart-chrony

    - name: Be sure chrony is running and enabled
      become: true
      ansible.builtin.service:
        name: "{{ (ansible_os_family in ['Debian','Ubuntu']) | ternary('chrony', 'chronyd') }}"
        state: started
        enabled: true
  tags: ['chrony']

# В RedHat пакет rsyslog создает файл syslog в logrotate.d, другие — rsyslog
- name: LOGROTATE | Rsyslog rotate settings
  become: true
  ansible.builtin.template:
    src: templates/logrotate.d/rsyslog
    dest: "/etc/logrotate.d/{{ (ansible_os_family == 'RedHat') | ternary('syslog', 'rsyslog') }}"
    owner: root
    group: root
    mode: '0644'
  when: ansible_os_family == "RedHat"
  tags: ['logrotate']

- name: RSYSLOG | service templating
  block:
    - name: Be sure rsyslog is installed
      become: true
      ansible.builtin.package:
        name: rsyslog
        state: present

    - name: Be sure rsyslog is configured
      become: true
      ansible.builtin.template:
        src: templates/rsyslog.d/log_main.j2.conf
        dest: /etc/rsyslog.d/log_main.conf
        owner: root
        group: root
        mode: '0644'
      notify: restart-rsyslog
  tags: ['rsyslog']

- name: AUDITD | rule templating
  block:
    - name: Be sure auditd is installed
      become: true
      ansible.builtin.package:
        name: auditd
        state: present

    - name: Check existing audit rules
      become: true
      ansible.builtin.stat:
        path: "{{ (ansible_os_family in ['Debian','Ubuntu']) | ternary('/etc/audit/audit.rules', '/etc/audit/rules.d/audit.rules') }}"
      register: audit_rules_check

    - name: Backup original audit rules
      become: true
      ansible.builtin.copy:
        src: "{{ (ansible_os_family in ['Debian','Ubuntu']) | ternary('/etc/audit/audit.rules', '/etc/audit/rules.d/audit.rules') }}"
        dest: /etc/audit/audit.rules.orig
        remote_src: yes
        owner: root
        group: root
        mode: '0600'
      when: audit_rules_check.stat.exists

    - name: Be sure recommended audit rules applied
      become: true
      ansible.builtin.template:
        src: files/auditd/audit.rules
        dest: "{{ (ansible_os_family in ['Debian','Ubuntu']) | ternary('/etc/audit/audit.rules', '/etc/audit/rules.d/audit.rules') }}"
        owner: root
        group: root
        mode: '0600'
      notify: systemd-restart-auditd
  tags: ['auditd']

- name: JOURNALD | rotate settings
  become: true
  ansible.builtin.template:
    src: templates/systemd/journald.conf
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart-journald
  tags: ['journald']

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
