---
- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Check if SELinux is NOT allowed on Debian-based systems
  ansible.builtin.set_fact:
    selinux_allowed: false
  when:
    - not selinux_enabled | default(false)
    - ansible_distribution in ['Ubuntu', 'Debian']

# Отключаем SELinux только на системах, где это возможно. В Debian like OS нет зависимых python se библиотек.
- name: Disable SELinux
  become: true
  ansible.posix.selinux:
    state: disabled
  when:
    - not selinux_allowed | default(true) | bool
    - ansible_distribution not in ['Ubuntu', 'Debian']
  tags: ['selinux']

- name: Check up any old failed systemd units
  become: true
  ansible.builtin.command:
    cmd: systemctl reset-failed