---
- name: Check if SELinux is disabled
  become: true
  ansible.posix.selinux:
    policy: targeted
    state: enforcing
  register: selinux

- name: Reboot if required
  become: true
  ansible.builtin.reboot:
    reboot_timeout: 300
  when: selinux.reboot_required

- name: Allow kernel modules
  become: true
  ansible.posix.seboolean:
    name: domain_kernel_load_modules
    state: false
    persistent: true
