---
- name: USERS | Be sure user exists
  become: true
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.comment | default('') }}"
    password: "{{ (item.password | default('')) if (allow_user_passwords|bool) else omit }}"
    group: "{{ item.group | default('') }}"
    password_expire_min: "{{ '7' if (allow_user_passwords|bool and item.password is defined) else omit }}"
    state: "{{ item.state | default('present') }}"
    remove: true
  when: common_users_list is defined
  loop: "{{ common_users_list }}"
  loop_control:
    label: "{{ item.name }}"

- name: USERS | Be sure authorized key is set for user
  become: true
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.key | default('') }}"
    state: present
  when:
    - common_users_list is defined
    - (item.state is defined and item.state == 'present') or item.state is not defined
  loop: "{{ common_users_list }}"
  loop_control:
    label: "{{ item.name }}"
