---
all:
###################################################################################################
### GLOBAL VARS ###################################################################################
  vars:
    ansible_port: 22

###################################################################################################
### ALL HOSTS #####################################################################################
  children:
    
    ###############################################################################################
    ### LOCAL GROUP ###############################################################################
    local:
      hosts:
        devlcl1t01:
          ansible_host: 127.0.0.1
          ansible_connection: local
      vars:
        environment: test
        selinux_enabled: false

    ###############################################################################################
    ### MICROK8S GROUP ############################################################################
    microk8s:
      hosts:
        devk3s1t01:
          ansible_host: 10.211.55.18
      vars:
        environment: test
        selinux_enabled: false
