---
- name: Common playbook to preconfigure RHEL / REDOS hosts
  hosts: "{{ target | default('all') }}"
  gather_facts: true
  become: false

  tasks:
    - name: Check variable definitions
      ansible.builtin.assert:
        that: "{{ item }} is defined"
        fail_msg: "Have to specify {{ item }} global host variable"
      loop:
        - environment
        - selinux_enabled

    - name: COMMON | Including main preconfigure role
      ansible.builtin.include_role:
        name: common
      when: true
    
    - name: KESL | Including kesl agent setup role
      ansible.builtin.include_role:
        name: kesl-agent
      when: false
    
    - name: ZABBIX | Including zabbix agent setup role
      ansible.builtin.include_role:
        name: zabbix-agent
      when: false