---
- name: Install Asciidoctor
  become: no #Running Homebrew as root no longer supported
  homebrew: 
    name: asciidoctor
    state: present
  when: 
    - homebrew_ready
  register: asciidoctor_status

- debug:
    var: asciidoctor_status
