---
- name: Ensuring Homebrew Is Installed on Intel
  stat:
    path: /usr/local/bin/brew
  register: homebrew_intel_check

- name: Ensuring Homebrew Is Installed on ARM
  stat:
    path: /opt/homebrew/bin/brew
  register: homebrew_arm_check

- name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
  fail:
    msg: Homebrew is missing, install from http://brew.sh
  when:
    - not homebrew_intel_check.stat.exists
    - not homebrew_arm_check.stat.exists
    - not install_homebrew_if_missing

- name: Installing Homebrew
  shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  when:
    - not homebrew_intel_check.stat.exists
    - not homebrew_arm_check.stat.exists
    - install_homebrew_if_missing
  register: homebrew_ready | bool

- debug:
    msg: "Homebrew is installed == {{ homebrew_ready.stdout }}"
